title: AI and Scientific Discovery Workshop
description: Workshop on AI and Scientific Discovery
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-144588579-1
